import { Sparkles, Trash2, UserPlus } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'

import { ChartFrame, LegendItem, RoastBarChart, BarTable } from '../components/charts'
import {
  Button,
  Card,
  ConfirmDialog,
  EmptyState,
  Field,
  Input,
  Modal,
  Select,
  Skeleton,
} from '../components/ui'
import { ApiError, api } from '../lib/api'
import { useAuth } from '../lib/auth'
import { formatDate, initials } from '../lib/format'
import { useToast } from '../lib/toast'
import type { Insight, LeaderboardRow, Role, User } from '../lib/types'

export function Team() {
  const { user: me, isAdmin } = useAuth()
  const toast = useToast()
  const [users, setUsers] = useState<User[]>([])
  const [board, setBoard] = useState<LeaderboardRow[]>([])
  const [weekly, setWeekly] = useState<Insight | null>(null)
  const [loading, setLoading] = useState(true)
  const [inviting, setInviting] = useState(false)
  const [deleting, setDeleting] = useState<User | null>(null)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const [u, b, w] = await Promise.all([
        api.listUsers(),
        api.leaderboard(30).catch(() => []),
        api.weekly().catch(() => null),
      ])
      setUsers(u)
      setBoard(b)
      setWeekly(w)
    } catch {
      toast.error('Could not load the team.')
    } finally {
      setLoading(false)
    }
  }, [toast])

  useEffect(() => {
    void load()
  }, [load])

  const changeRole = async (u: User, role: Role) => {
    try {
      const updated = await api.updateUser(u.id, { role })
      setUsers((list) => list.map((x) => (x.id === u.id ? updated : x)))
      toast.success(`${u.name} is now ${role}.`)
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Could not change the role.')
    }
  }

  const toggleActive = async (u: User) => {
    try {
      const updated = await api.updateUser(u.id, { is_active: !u.is_active })
      setUsers((list) => list.map((x) => (x.id === u.id ? updated : x)))
      toast.success(updated.is_active ? 'Account reactivated.' : 'Account deactivated.')
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Could not update the account.')
    }
  }

  const remove = async () => {
    if (!deleting) return
    try {
      await api.deleteUser(deleting.id)
      setUsers((list) => list.filter((x) => x.id !== deleting.id))
      toast.success('Team member removed.')
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Could not remove the member.')
    } finally {
      setDeleting(null)
    }
  }

  const boardBars = board.map((r) => ({ label: r.name, value: r.activities }))

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl text-latte">Team</h1>
          <p className="mt-1 text-sm text-latte/50">
            {loading ? 'Loading…' : `${users.length} member${users.length === 1 ? '' : 's'}`}
          </p>
        </div>
        {isAdmin && (
          <Button onClick={() => setInviting(true)} icon={<UserPlus size={15} />}>
            Add member
          </Button>
        )}
      </div>

      {/* Weekly AI highlights */}
      <Card className="border-gold/25 bg-gold/[0.05]">
        <div className="mb-3 flex items-center gap-2.5">
          <Sparkles size={17} className="text-gold" />
          <div>
            <h2 className="font-display text-lg text-latte">Weekly Performance Highlights</h2>
            <p className="text-[11px] text-latte/45">
              {weekly?.model ? `Generated by ${weekly.model}` : 'Claude Haiku'}
            </p>
          </div>
        </div>
        {weekly ? (
          <ul className="space-y-2">
            {weekly.content
              .split('\n')
              .map((l) => l.replace(/^[-•*]\s*/, '').trim())
              .filter(Boolean)
              .map((line, i) => (
                <li key={i} className="flex gap-3 text-sm leading-relaxed text-latte/75">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-gold" />
                  {line}
                </li>
              ))}
          </ul>
        ) : (
          <p className="py-4 text-center text-sm text-latte/40">
            Weekly highlights are not available right now.
          </p>
        )}
      </Card>

      {/* Leaderboard */}
      {boardBars.length > 0 && (
        <ChartFrame
          title="Interactions Logged"
          subtitle="Per team member, last 30 days"
          legend={<LegendItem color="#DCAB63" label="Interactions" />}
          table={<BarTable data={boardBars} unit="Interactions" />}
        >
          <RoastBarChart data={boardBars} unit="interactions" />
        </ChartFrame>
      )}

      {/* Members */}
      {loading ? (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-32 w-full" />
          ))}
        </div>
      ) : users.length === 0 ? (
        <EmptyState emoji="👥" title="No team members yet" />
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {users.map((u) => (
            <Card key={u.id} ripple className={u.is_active ? '' : 'opacity-55'}>
              <div className="flex items-start gap-3">
                <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-gold-gradient text-sm font-bold text-bean">
                  {initials(u.name)}
                </div>
                <div className="min-w-0 flex-1">
                  <p className="truncate font-medium text-latte">
                    {u.name}
                    {u.id === me?.id && <span className="ml-1.5 text-[11px] text-gold">you</span>}
                  </p>
                  <p className="truncate text-[11px] text-latte/45">{u.email}</p>
                  <p className="mt-0.5 text-[10px] text-latte/30">
                    Joined {formatDate(u.created_at)}
                  </p>
                </div>
              </div>

              <div className="mt-4 flex items-center gap-2 border-t border-caramel/12 pt-3">
                {isAdmin && u.id !== me?.id ? (
                  <>
                    <Select
                      value={u.role}
                      onChange={(e) => changeRole(u, e.target.value as Role)}
                      options={[
                        { value: 'employee', label: 'Employee' },
                        { value: 'manager', label: 'Manager' },
                        { value: 'admin', label: 'Admin' },
                      ]}
                      className="!py-1.5 text-xs"
                    />
                    <button
                      onClick={() => toggleActive(u)}
                      className="shrink-0 rounded-lg border border-caramel/25 px-2.5 py-1.5 text-[11px] text-latte/60 transition hover:border-gold/45 hover:text-latte"
                    >
                      {u.is_active ? 'Disable' : 'Enable'}
                    </button>
                    <button
                      onClick={() => setDeleting(u)}
                      className="shrink-0 rounded-lg p-2 text-latte/40 transition hover:bg-red-500/15 hover:text-red-300"
                      aria-label={`Remove ${u.name}`}
                    >
                      <Trash2 size={14} />
                    </button>
                  </>
                ) : (
                  <span className="chip border-caramel/25 bg-bean/40 capitalize text-latte/60">
                    {u.role}
                  </span>
                )}
              </div>
            </Card>
          ))}
        </div>
      )}

      <InviteModal
        open={inviting}
        onClose={() => setInviting(false)}
        onCreated={(u) => {
          setUsers((list) => [u, ...list])
          setInviting(false)
        }}
      />

      <ConfirmDialog
        open={!!deleting}
        title="Remove this team member?"
        message={`${deleting?.name} will lose access to BeviGrow. Their logged interactions stay on the accounts.`}
        confirmLabel="Remove"
        onConfirm={remove}
        onCancel={() => setDeleting(null)}
      />
    </div>
  )
}

function InviteModal({
  open,
  onClose,
  onCreated,
}: {
  open: boolean
  onClose: () => void
  onCreated: (u: User) => void
}) {
  const toast = useToast()
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [role, setRole] = useState<Role>('employee')
  const [busy, setBusy] = useState(false)
  const [errors, setErrors] = useState<Record<string, string>>({})

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    const errs: Record<string, string> = {}
    if (!name.trim()) errs.name = 'Name is required'
    if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) errs.email = 'Enter a valid email'
    if (password.length < 8) errs.password = 'At least 8 characters'
    setErrors(errs)
    if (Object.keys(errs).length) return

    setBusy(true)
    try {
      const u = await api.createUser({ name: name.trim(), email: email.trim(), password, role })
      toast.success(`${u.name} can now sign in.`)
      setName('')
      setEmail('')
      setPassword('')
      onCreated(u)
    } catch (err) {
      toast.error(err instanceof ApiError ? err.message : 'Could not create the account.')
    } finally {
      setBusy(false)
    }
  }

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Add a team member"
      subtitle="They can sign in immediately with these credentials"
      width="max-w-lg"
    >
      <form onSubmit={submit} noValidate className="space-y-4">
        <Field label="Full name *" error={errors.name}>
          <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Priya Sharma" />
        </Field>
        <Field label="Email *" error={errors.email}>
          <Input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="priya@bevigrow.com"
          />
        </Field>
        <Field label="Temporary password *" error={errors.password} hint="Minimum 8 characters">
          <Input
            type="text"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="ChangeMe123"
          />
        </Field>
        <Field label="Role">
          <Select
            value={role}
            onChange={(e) => setRole(e.target.value as Role)}
            options={[
              { value: 'employee', label: 'Employee — log activity, manage own accounts' },
              { value: 'manager', label: 'Manager — full account access' },
              { value: 'admin', label: 'Admin — full access including team management' },
            ]}
          />
        </Field>
        <div className="flex justify-end gap-3 border-t border-caramel/15 pt-4">
          <Button type="button" variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          <Button type="submit" loading={busy}>
            Create account
          </Button>
        </div>
      </form>
    </Modal>
  )
}
